development:
  adapter: postgresql
  encoding: unicode
  database: my_development
  pool: 5
  port: 5433
  # username: chaya
  password: cafeonlineordering
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5433
  host: <%= ENV['DATABASE_HOST'] %>
  database: my_production
  # username: chaya
  password: cafeonlineordering